### PR TITLE
[Buildkite] Setting up CI to test the library on Pull Requests

### PR DESCRIPTION
**Pull request by jsanz**
This PR adds the pipeline to run the tests suite and build the library.

~Initially is using the default CI image but I've started a PR to our CI team to get a custom Docker image that will include the `yarn` command so we don't need to install it on every build. We will refine that in a follow-up PR.~

The pipeline uses a custom agent Docker image that includes support for running `yarn` and `gcloud`.

The Pull Requests configuration should give us the ability to trigger builds from comments, but also skip them if the `skip-ci` label is added, or if the changed files are not relevant (markdown files and CI settings).

### CODE REVIEW

**Comment by jsanz** [comment]
@nickpeihl given the project is quite straight forward and not pushing anything into production or external components, what do you think of also removing the Jenkins settings here?

**Comment by nickpeihl** [comment]
> @nickpeihl given the project is quite straight forward and not pushing anything into production or external components, what do you think of also removing the Jenkins settings here?

Sounds good to me. We don't have any pending or planned PRs, so we should be able to create the buildkite pipelines and remove the jenkins settings in the same PR.  👍

**Comment by jsanz** [comment]
> Sounds good to me. We don't have any pending or planned PRs, so we should be able to create the buildkite pipelines and remove the jenkins settings in the same PR. +1

Something we have in our current CI is a daily build of `master` even I'm not sure this is necessary. Do you think it is OK to just run builds on PRs, or should we also run builds on merges and/or schedule to `master`?

**Comment by nickpeihl** [comment]
I suggest we only run builds on PRs and schedule weekly builds on master. Our PRs are infrequent and we would rarely have a situation where CI on master would break. I think the only danger is if we let a PR sit for too long without merging changes from master. But a weekly build on master should resolve that.

**Comment by jsanz** [comment]
@nickpeihl I agree on weekly builds, thanks for the feedback. That is something to set up in the CI repository, so nothing here should be changed.

On a second thought, I'll leave the removal of Jenkins CI jobs for another PR so we are sure we get a working Buildkite integration and no PR is left with visual feedback on the results of the tests.

**Review by nickpeihl — APPROVED** [review]
lgtm! 🤞

**Comment by jsanz** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.4|[](https://github.com/elastic/ems-client/pull/161)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
