### PR TITLE
[Maps] Export FileLayerField

### PR DESCRIPTION
**Pull request by thomasneirynck**
Closes https://github.com/elastic/ems-client/issues/71

### CODE REVIEW

**Review by nickpeihl — APPROVED** [review]
lgtm! 

should this go into a 7.14 patch or wait until 7.15.0?

**Comment by thomasneirynck** [comment]
> should this go into a 7.14 patch or wait until 7.15.0?

7.15.0 is OK. Will remove shim from Kibana then as well.

**Comment by nickpeihl** [comment]
@thomasneirynck do you want to merge this? there is no 7.x branch so no need to backport it.

**Comment by thomasneirynck** [comment]
thx @nickpeihl I'd forgotten

**Pull request merged**
